
before_script:
  - pip install .

stages:
  - test
  - deploy

test_python3.11:
    only:
      - master
      - merge_requests
    stage: test
    image: python:3.11-buster
    script:
    - python -m pytest tests

test_python3.9:
    only:
      - master
      - merge_requests
    stage: test
    image: python:3.9-buster
    script:
    - python -m pytest tests

test_python3.10:
    only:
      - master
      - merge_requests
    stage: test
    image: python:3.10-buster
    script:
    - python -m pytest tests

coverage:
    only:
        refs:
        - master
        - dev
    image: python:3.12-rc-buster
    stage: test
    script:
      - pip install pytest pytest-cov
      - pytest --cov --cov-report term --cov-report xml:coverage.xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        reports:
          coverage_report:
            coverage_format: cobertura
            path: coverage.xml

pypi_deploy:
  stage: deploy
  only:
    - tags
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel

  script:
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
