image: python:3.7.5-slim-buster

before_script:
  - pip install .

stages:
  - build
  - test

build:
    only:
        refs:
        - master
        - dev
    stage: build
    script:
    - python -m pytest tests

coverage:
    only:
        refs:
        - master
        - dev
    stage: test
    script:
      - pytest --cov mlmc/ tests/ --cov-report xml
      - coverage report

pages:
    - pdoc3 --config show_source_code=False -o public mlmc