
before_script:
  - pip install .

stages:
  - test
  - build
  - deploy



coverage:
    only:
        refs:
        - master
        - dev
    image: python:3.7.5-slim-buster
    stage: test
    script:
      - pytest --cov mlmc/ tests/ --cov-report xml
      - coverage report

test_python3.7:
    only:
      - master
      - tags
      - merge_requests
      - dev
    stage: build
    image: python:3.7.5-slim-buster
    script:
    - python -m pytest tests

test_python3.8:
    only:
      - master
      - tags
      - merge_requests
      - dev
    stage: build
    image: python:3.8-buster
    script:
    - python -m pytest tests


build:
    only:
      - master
      - dev
    stage: build
    image: python:3.7.5-slim-buster
    script:
    - python -m pytest tests


pypi_deploy:
  stage: deploy
  only:
    - tags
  image: python:3.7-stretch
  before_script:
    - pip install -r requirements.txt
    - python setup.py sdist bdist_wheel

  script:
    - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*

