image: python:3.7.5-slim-buster

before_script:
  - echo $(pwd)
  - pip install .

stages:
  - build
  - test

build:
    only:
        refs:
        - master
        - dev
  stage: build
  script:
    - python -m pytest tests

coverage:
    only:
        refs:
        - master
        - dev
    stage: test
    script:
      - pytest --cov mlmc/ tests/ --cov-report xml
      - coverage report
